###
# Bellabeat analysis case study!
# Author: Linda Perez Jaracuaro
# Date: November 2nd 2023
###

# How Can a Wellness Technology Company Play It Smart?
# focus on a Bellabeat product and analyze smart device usage data in order to 
# gain insight into how people are already using their smart devices. 
# Then, using this information, she would like high-level recommendations for 
# how these trends can inform Bellabeat marketing

# Set working directory
setwd("./Bellabeat")

# 1. Ask ------------------------------------------------------------------

# 1. What are some trends in smart device usage?
# 2. How could these trends apply to Bellabeat customers?
# 3. How could these trends help influence Bellabeat marketing strategy?

# 2. Prepare -----------------------------------------------------------------

# Data Source: Ride data

# Type of Data: Time-series data
# Format: CSV file
# License: CC0 Public Domain
# Collection Period: 03.12.2016-05.12.2016
# Description: This dataset generated by respondents to a distributed survey via
# Amazon Mechanical Turk between 03.12.2016-05.12.2016. Thirty eligible Fitbit 
# users consented to the submission of personal tracker data, including 
# minute-level output for physical activity, heart rate, and sleep monitoring. 
# Individual reports can be parsed by export session ID (column A) or timestamp 
# (column B). Variation between output represents use of different types of 
# Fitbit trackers and individual tracking behaviors / preferences.


# Include libraries
library(lubridate)
library(purrr)
library(scales)
library(tidyverse)
library(waterfalls)

# Add all daily available data using REGEX pattern
daily_files <- list.files(path = "./Data files",
                           pattern = "daily\\w+_merged\\.csv$",
                           full.names = TRUE)
daily_list <- lapply(daily_files, read.csv)
# Create a dataframe for daily data using common Id and ActivityDate values
daily_df <- daily_list %>%
  reduce(left_join)
# Remove unnecesary variables
rm(daily_files, daily_list)

# Add all hourly available data using REGEX pattern
hourly_files <- list.files(path = "./Data files",
                    pattern = "hourly\\w+_merged\\.csv$",
                    full.names = TRUE)
hourly_list <- lapply(hourly_files, read.csv)
# Create a dataframe for hourly data using common Id and ActivityDate values
hourly_df <- hourly_list %>%
  reduce(full_join, by = c("Id", "ActivityHour"))
# Remove unnecesary variables
rm(hourly_files, hourly_list)

# Add all minute available data using REGEX pattern
minutely_files <- list.files(path = "./Data files",
                           pattern = "minute\\w+_merged\\.csv$",
                           full.names = TRUE)
minutely_list <- lapply(minutely_files, read.csv)
# Create a dataframe for minute data using common Id and ActivityMinute values
minutely_df <- minutely_list %>%
  reduce(full_join, by = c("Id", "ActivityMinute"))
# Remove unnecesary variables
rm(minutely_files, minutely_list)

# Add heartrate, sleep and weight data as data frames
heartrate_df = read.csv('./Data files/heartrate_seconds_merged.csv')
sleep_df = read.csv('./Data files/sleepDay_merged.csv')
weight_df = read.csv('./Data files/weightLogInfo_merged.csv')


rm(hourly_df, minutely_df)

# 3. Process --------------------------------------------------------------

#  Check if TotalDistance variable has the same observations with TrackerDistance
all(daily_df$TotalDistance == daily_df$TrackerDistance)
distance_difference <- daily_df %>%
  summarise(TotalDistance,TrackerDistance, LoggedActivitiesDistance) %>%
  filter(TotalDistance != TrackerDistance)

# Check if TotalSteps variable has the same observations with StepsTotal
all(daily_df$TotalSteps == daily_df$StepsTotal)
daily_df <- daily_df %>%
  select(-StepTotal)

# Remove repeated variables from the dataset
daily_df <- daily_df %>%
  select(-SedentaryMinutes, -LightlyActiveMinutes, -FairlyActiveMinutes)

# Add a variable for TotalTime
daily_df <- daily_df %>%
  group_by(Id, ActivityDay) %>%
  mutate(TotalTime = sum(VeryActiveMinutes, ModeratelyActiveMinutes, 
                         LightActiveMinutes, SedentaryActiveMinutes))

# Parse date into date format
daily_df$ActivityDay <- strptime(daily_df$ActivityDay, format = "%m/%d/%Y")
#add column to show week number
daily_df$WeekNum <- strftime(daily_df$ActivityDay, format = "%V")

# Add a new variable that computes weekday per observation
daily_df <- daily_df %>%
  mutate(
    DayOfWeek = wday(ActivityDay,
                       label = TRUE)
  )

# Parse date into date format
heartrate_df$ActivityDay <- strptime(heartrate_df$Time, format = "%m/%d/%Y %I:%M:%S %p")
# Split date and time
heartrate_df$Date <- as.Date(heartrate_df$ActivityDay)
heartrate_df$Time <- format(heartrate_df$ActivityDay, format = "%I:%M:%S")

# Parse date into date format
# Extract only date variable since time has a unique observation per day
sleep_df$Date <- strptime(sleep_df$Date, format = "%m/%d/%Y %I:%M:%S %p") %>%
  as.Date()

# Get user Id per category
id_list <- intersect(unique(daily_df$Id), unique(hourly_df$Id)) %>%
  intersect(minutely_df$Id)
id_heartrate <- heartrate_df$Id %>%
  unique()
id_sleep <- sleep_df$Id %>%
  unique()
id_weight <- weight_df$Id %>%
  unique()


# Check if heart rate ids are in id_list
if (all(id_heartrate %in% id_list)) {
  cat(TRUE)
} else {
  cat(FALSE)
}
# Check if sleep ids are in id_list
if (all(id_weight %in% id_list)) {
  cat(TRUE)
} else {
  cat(FALSE)
}
# Check if weight ids are in id_list
if (all(id_weight %in% id_list)) {
  cat(TRUE)
} else {
  cat(FALSE)
}

# Since all ids exists in id_list remove unneeded lists
rm(id_heartrate, id_sleep, id_weight)

# 4. Analyze --------------------------------------------------------------

# Create a Vector with each possible activity name in daily_df
sum_rownames <- c("Very", "Moderately", "Light", "Sedentary")

# Create a new data frame for computing distance values
daily_distance <- daily_df %>%
  filter(TotalDistance > 0)

# Create vectors for basics stats: total, mean, median and mode
total_distance <- c( sum(daily_distance$VeryActiveDistance), 
                     sum(daily_distance$ModeratelyActiveDistance),
                     sum(daily_distance$LightActiveDistance),
                     sum(daily_distance$SedentaryActiveDistance))
mean_distance <- c( mean(daily_distance$VeryActiveDistance), 
                     mean(daily_distance$ModeratelyActiveDistance),
                     mean(daily_distance$LightActiveDistance),
                     mean(daily_distance$SedentaryActiveDistance))
median_distance <- c( median(daily_distance$VeryActiveDistance), 
                     median(daily_distance$ModeratelyActiveDistance),
                     median(daily_distance$LightActiveDistance),
                     median(daily_distance$SedentaryActiveDistance))

# # Create a summary for distance variables
# sum_distance <- tibble(
#   total = total_distance,
#   mean = mean_distance,
#   median = median_distance
# )
# rownames(sum_distance) <- sum_rownames

# Create a data frame for the sum of each activity level
distance_df <- tibble(
  ActivityLevel = sum_rownames,
  Total = round(total_distance,2)
)

# Remove unused vectors
rm(daily_distance, total_distance, mean_distance, median_distance)
  
# Create a new data frame for computing time values
weekly_activity_time <- daily_df %>%
  filter(TotalTime > 0) %>%
  ungroup() %>%
  group_by(Id, WeekNum) %>%
  summarise( Very = sum(VeryActiveMinutes),
             Moderately= sum(ModeratelyActiveMinutes),
             SumVeryModerately = sum(Very, Moderately),
             Light = sum(LightActiveMinutes),
             Sedentary = sum(SedentaryActiveMinutes),
             Total = sum(TotalTime))

# Get total of users that exercise more than 150 minutes per week
healthy_users <- weekly_activity_time %>%
  summarise(Total = mean(SumVeryModerately)) %>%
  filter(Total >= 150) %>%
  nrow()
# Get total users
total_users <- length(id_list)
# Compute the percentage
healthy_perc <- round((healthy_users / total_users) * 100, 1)
unhealthy_perc <- 100 - healthy_perc
# Remove used variables
rm(healthy_users)


# Create a summary of steps per user
daily_steps <- daily_df %>%
  ungroup() %>%
  select(Id, TotalSteps) %>%
  group_by(Id) %>%
  summarise(MeanSteps = mean(TotalSteps))

# Create a new data frame that classifies users by mean steps per day
# https://pubmed.ncbi.nlm.nih.gov/32207799/
# The unadjusted incidence density for all-cause mortality was 
# 76.7  less than 4000 steps per day; 
# 21.4  4000 to 7999 steps per day; 
# 6.9   8000 to 11 999 steps per day; and 
# 4.8   at least 12 000 steps per day.
relative_risk <- data.frame(
  Risk = c(76.7, 21.4, 6.9, 4.8),
  Steps = factor(
    c("Less than 4000", "4000 to 7999", "8000 to 11999", "12000 and more"),
    levels = c("Less than 4000", "4000 to 7999", "8000 to 11999", "12000 and more"),
    ordered = TRUE
  )
)
  
mortality_risk_steps <- daily_steps %>%
  mutate(
    RelativeRisk = case_when(
      MeanSteps < 4000 ~ "Sedentary",
      MeanSteps >= 4000 & MeanSteps < 8000 ~ "Low",
      MeanSteps >= 8000 & MeanSteps < 12000 ~ "Moderate",
      MeanSteps >= 12000 ~ "High",
      TRUE ~ as.character(NA_real_)
    )
  ) %>%
  group_by(RelativeRisk) %>%
  summarise(
    Users = n(),
    UsersPerc = round(n() / nrow(daily_steps) * 100, 1)
  )

sum_sleep <- sleep_df %>%
  group_by(Id) %>%
  summarise(Total = mean(TotalMinutesAsleep))

# Get total of users that exercise more than 150 minutes per week
healthy_sleep_users <- sum_sleep %>%
  filter(Total >= 420) %>%
  nrow()
# Compute the percentage
healthy_sleep_perc <- round((healthy_sleep_users / total_users) * 100, 1)
unhealthy_sleep_perc <- 100 - healthy_sleep_perc
# Remove used variables
rm(healthy_sleep_users)

steps_by_weekday <- daily_df %>%
  ungroup() %>%
  select(Id, DayOfWeek, TotalSteps) %>%
  filter(TotalSteps != 0) %>%
  group_by(DayOfWeek) %>%
  summarize(
    mean = mean(TotalSteps),
    min = min(TotalSteps),
    max = max(TotalSteps)
  )


#STEPS
# Step intensity (number of steps per minute) didn’t influence the risk of 
#death, suggesting that the total number of steps per day is more important 
#than intensity.

#Taking 4,000 or fewer steps a day is considered a low level of physical activity.

# Compared with people who took 4,000 steps a day, those who took 8,000 steps a 
# day at the start of the study had a 50% lower risk of dying from any cause 
# during follow-up. People who took 12,000 steps a day had a 65% lower risk of 
# dying than those who took only 4,000.

# Source: https://www.nih.gov/news-events/nih-research-matters/number-steps-day-more-important-step-intensity


# 5. Share ----------------------------------------------------------------

palette <- c("#bebebe","#bebebe","#bebebe","#bebebe")
palette_highlight <- "#3d93a2"


# Mortality risk user composition - Waterfall char
waterfall(mortality_risk_steps,
          fill_by_sign = FALSE,
          fill_colours = palette) +
  labs(title = "Activity Level by steps",
       subtitle = "Steps average per day registered per 33 eligible users during three months",
       caption = "Based on a representative sample of US adults, a greater number of daily steps was significantly associated with lower all-cause mortality.") +
  theme_void()+
  theme(legend.title = element_blank(), 
        axis.text.x = element_text())

# https://pubmed.ncbi.nlm.nih.gov/32207799/
# The unadjusted incidence density for all-cause mortality was 
# 76.7  less than 4000 steps per day; 
# 21.4  4000 to 7999 steps per day; 
# 6.9   8000 to 11 999 steps per day; and 
# 4.8   at least 12 000 steps per day.

# Time breakdown by activity type - waterfall chart
waterfall(sum_time, 
          calc_total = TRUE,
          fill_by_sign = FALSE,
          fill_colours = palette,
          rect_border = NA,
          total_rect_color = palette_highlight,
          total_rect_border_color = NA,
          draw_lines = FALSE) + 
  labs(title = "Time breakdown",
       subtitle = "Sum of kilometers registered per 33 eligible users during three months") +
  scale_linetype_manual(aesthetics = palette) +
  theme_void() +
  theme(legend.title = element_blank(), 
        axis.text.x = element_text())
# TIME
# The U.S. Department of Health and Human Services recommends 150 minutes a 
# week of moderate-intensity exercise, such as brisk walking.

# # Distance breakdown by activity type - line horizontal chart
# ggplot(data = sum_time,
#        mapping = aes(x = ActivityLevel,
#                      y = Total,
#                      group = 1)) + 
#   geom_line(colour = palette_highlight) + 
#   geom_point(colour = palette_highlight) +  
#   scale_y_continuous(labels = unit_format(unit = "", scale = 1e-3),
#                      limits = c(0, 1000000)) +
#   labs(title = "Distance rate by activity level",
#        subtitle = "Sum of kilometers registered per 33 eligible users during three months",
#        y = "",
#        x = "") +
#   theme_classic()
# 
# # Distance breakdown by activity type - bar horizontal chart
# ggplot(data = sum_time,
#        mapping = aes(x = ActivityLevel,
#                      y = Total,
#                      group = 1)) + 
#   geom_col(fill = palette_highlight) + 
#   scale_y_continuous(labels = unit_format(unit = "", scale = 1e-3),
#                      limits = c(0, 1000000)) +
#   labs(title = "Distance rate by activity level",
#        subtitle = "Sum of kilometers registered per 33 eligible users during three months",
#        y = "",
#        x = "") +
#   theme_classic()
# 
# # Distance breakdown by activity type - waterfall chart
# waterfall(distance_df, 
#           calc_total = TRUE,
#           fill_by_sign = FALSE,
#           fill_colours = palette,
#           rect_border = NA,
#           total_rect_color = palette_highlight,
#           total_rect_border_color = NA,
#           draw_lines = FALSE) + 
#   labs(title = "Distance breakdown",
#        subtitle = "Sum of kilometers registered per 33 eligible users during three months") +
#   scale_linetype_manual(aesthetics = palette) +
#   theme_void() +
#   theme(legend.title = element_blank(), 
#         axis.text.x = element_text())
# 
# # Distance breakdown by activity type - boxplot chart
# # boxplot(daily_distance$TotalDistance)

